### ISSUE TITLE
I can't create a new backend session

### ISSUE THREAD

**Issue by marioswim** [alejcas/flask-session-plus#3]
I'm trying to create a new backend session using redis but with other serializer. But with the information available about add new backend session i can't do it.

Shall you increase the information about this please?

**Comment by alejcas** [comment]
If you read the code you will figure this out really fast.

Simply subclass the backend and asign your desired serializer

**Comment by marioswim** [comment]
Okey thanks

Furthemore, i dont understand the code in the session.py file between the lines 70 to 74.  After debugging the code, i found out the next behavior

when i dont define any field in "session_fields" variable, but the session was modified, how  "modified" variable is initialized to false in the line 70 and the object has not any field in "session_fields" variable, the loop won't be executed.

In the next lines the session will be marked as not modified in the "new_session" variable due to first value of "modified" variable and the session wont be stored due to the modification flag is set to false

however, when i define at least a field in "session_fields" variable, the execution run fine when i modified the session because the execution enter inside the loop in the line 71  and the "modified" variable is modificated.

Finally, i'm being forced to set at least a field in the "session_config" variable when this variables is not required

Thanks you in advance

**Comment by alejcas** [comment]
> Furthemore, i dont understand the code in the session.py file between the lines 70 to 74. After debugging the code

This piece of code is just setting the whole modified state of the session based on the individual fields marked as modified by the MultiSession object. Each Session has a modified state. This state must be set individually for each session backend based on the modified state of each session field that belongs to the session interface.


> when i dont define any field in "session_fields" variable, but the session was modified, how "modified" variable is initialized to false in the line 70 and the object has not any field in "session_fields" variable, the loop won't be executed.
> 
> In the next lines the session will be marked as not modified in the "new_session" variable due to first value of "modified" variable and the session wont be stored due to the modification flag is set to false
> 
> however, when i define at least a field in "session_fields" variable, the execution run fine when i modified the session because the execution enter inside de loop in the line 71 and the "modified" variable is modificated.
> 
> Finally, i'm being forced to set at least a field in the "session_config" variable when this variables is not required

**Yep I've realised now that the default `session_fields` value should be 'auto' instead of the current '[]' (empty list) value.**

However I don't have time right now to test this change and to modify the code. (If you want to change it and test it a PR will be welcome)

For the moment, you can just set the `session_fields` to a defined value (or 'auto' to include only the unused session fields by all the other session interfaces)

**Comment by marioswim** [comment]
Thank you so much for your time ;)


I don't know if this is an issue or it's intentional, but i have had to overwrite the function "get_expiration_time" in BaseSessionInterface class because it's returning a datetime object.
 
The code is failing because in the line 398 in backends.py (in my case, i'm using redis interface, but i think that fail for all interface) because the "total_seconds" function expect a timedelta object.

My solution was a redis interface subclass for overwrite the funciton:

```python
def get_expiration_time(self, app, session):
    if session.is_permanent(self.cookie_name):
        return timedelta(days=31)
    else:
        return self.session_lifetime
```

**Comment by alejcas** [comment]
It worked for me in the past as it is.
I'll check that

Thanks!

**Comment by marioswim** [comment]
you're welcome

Thank you so much for your time ;)

**Comment by marioswim** [comment]
you're welcome

Thank you so much for your time ;)
